# Generated by Django 5.0 on 2023-12-30 06:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("PA001_Deltares", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pa001PostgisFunción",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("comando", models.CharField(max_length=6)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "PA001_PostGis_función",
                "managed": False,
            },
        ),
        migrations.DeleteModel(
            name="Pa001PostgisFuncin",
        ),
    ]
