# Generated by Django 4.2.7 on 2023-12-02 11:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("PA001_Deltares", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="linkurl",
            name="Description",
            field=models.TextField(default="D"),
        ),
    ]
