# Generated by Django 3.2.22 on 2023-10-20 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PA001_Deltares', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resultfile',
            name='type_file',
        ),
        migrations.AlterField(
            model_name='resultfile',
            name='file',
            field=models.FileField(upload_to=''),
        ),
    ]
