# Generated by Django 3.2.22 on 2023-10-21 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PA001_Deltares', '0002_auto_20231020_1155'),
    ]

    operations = [
        migrations.CreateModel(
            name='imagefile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_GPPD', models.CharField(max_length=30)),
                ('f_name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
