# Generated by Django 3.2.22 on 2023-10-21 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PA001_Deltares', '0003_imagefile'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagefile',
            name='image_texto',
            field=models.CharField(default='html', max_length=255),
        ),
    ]
