# Generated by Django 3.2.22 on 2023-11-10 18:03

from django.db import migrations, models
import mapbox_location_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('PA001_Deltares', '0005_resultfile_type_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='TuModelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('ubicacion', mapbox_location_field.models.LocationField(map_attrs={'center': [-74.006, 40.7128]})),
            ],
        ),
    ]
