# Generated by Django 3.2.22 on 2023-11-11 14:22

from django.db import migrations
import mapbox_location_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('PA001_Deltares', '0007_auto_20231111_0754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tumodelo',
            name='ubicacion',
            field=mapbox_location_field.models.LocationField(default=[52.07049075585414, 4.305539240857647], map_attrs={'center': [52.07049075585414, 4.305539240857647]}),
        ),
    ]
