# Generated by Django 3.2.22 on 2023-11-11 14:24

from django.db import migrations
import mapbox_location_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('PA001_Deltares', '0008_alter_tumodelo_ubicacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tumodelo',
            name='ubicacion',
            field=mapbox_location_field.models.LocationField(default=[52.07, 4.3], map_attrs={'center': [52.07, 4.3]}),
        ),
    ]
