# Generated by Django 3.2.22 on 2023-11-13 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PA001_Deltares', '0011_alter_tumodelo_ubicacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tumodelo',
            name='ubicacion',
        ),
        migrations.AddField(
            model_name='tumodelo',
            name='latitud',
            field=models.DecimalField(decimal_places=6, default=52.07, max_digits=9),
        ),
        migrations.AddField(
            model_name='tumodelo',
            name='longitud',
            field=models.DecimalField(decimal_places=6, default=4.29, max_digits=9),
        ),
    ]
