# Generated by Django 3.2.22 on 2023-11-13 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PA001_Deltares', '0013_auto_20231113_0552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='points',
            name='latitud',
            field=models.FloatField(default=51.98595),
        ),
        migrations.AlterField(
            model_name='points',
            name='longitud',
            field=models.FloatField(default=4.38017),
        ),
    ]
