# Generated by Django 3.2.22 on 2023-11-15 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PA001_Deltares', '0014_auto_20231113_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='points',
            name='description',
            field=models.CharField(default='destription missing', max_length=250),
        ),
    ]
