# Generated by Django 3.2.22 on 2023-11-16 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PA001_Deltares', '0016_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkUrl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('url', models.URLField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'LinkUrls',
            },
        ),
        migrations.DeleteModel(
            name='Link',
        ),
    ]
